version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5433:5432'
  php:
    container_name: php
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '9002:9000'
    volumes:
      - ../logs/symfony:/var/www/symfony/var/logs:cached
    links:
      - postgres
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '1010:80'
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ../logs/nginx/:/var/log/nginx:cached
